/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Register;
import Login.LoginForm;
import java.awt.Font;
import javax.swing.JFrame;
import model.User;
import service.UserService;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import view.ListUserFrame;

/**
 *
 * @author Jonny Dam
 */
public class RegisterForm extends javax.swing.JFrame {
     UserService userService;
        User user; 
    public RegisterForm() {
        initComponents();
        
         userService = new UserService();
        user = new User();
//        Border black_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
//        Exit.setBorder(black_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        backgroundtitle = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        jalbel_fullname = new javax.swing.JLabel();
        textfield_username = new javax.swing.JTextField();
        jlabel_username = new javax.swing.JLabel();
        jlabel_password = new javax.swing.JLabel();
        textfield_fullname = new javax.swing.JTextField();
        jlabel_phone = new javax.swing.JLabel();
        textfield_email = new javax.swing.JTextField();
        textfield_phone = new javax.swing.JTextField();
        jlabel_email = new javax.swing.JLabel();
        jlabel_comfirmpassword = new javax.swing.JLabel();
        jbutton_register = new javax.swing.JButton();
        jPasswordField_password = new javax.swing.JPasswordField();
        jPasswordField_comfirmpassword = new javax.swing.JPasswordField();
        jlabel_loginnow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        backgroundtitle.setBackground(new java.awt.Color(51, 51, 51));
        backgroundtitle.setForeground(new java.awt.Color(245, 245, 245));
        backgroundtitle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        title.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Register");

        minimize.setBackground(new java.awt.Color(0, 0, 0));
        minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText("-");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(0, 0, 0));
        Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("X");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backgroundtitleLayout = new javax.swing.GroupLayout(backgroundtitle);
        backgroundtitle.setLayout(backgroundtitleLayout);
        backgroundtitleLayout.setHorizontalGroup(
            backgroundtitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundtitleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize)
                .addGap(18, 18, 18)
                .addComponent(Exit)
                .addGap(18, 18, 18))
        );
        backgroundtitleLayout.setVerticalGroup(
            backgroundtitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundtitleLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(backgroundtitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addGroup(backgroundtitleLayout.createSequentialGroup()
                        .addGroup(backgroundtitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minimize)
                            .addComponent(Exit))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        main.setBackground(new java.awt.Color(255, 255, 255));

        jalbel_fullname.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jalbel_fullname.setForeground(new java.awt.Color(51, 51, 51));
        jalbel_fullname.setText("Full Name");

        textfield_username.setBackground(new java.awt.Color(231, 231, 231));
        textfield_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textfield_username.setForeground(new java.awt.Color(51, 51, 51));
        textfield_username.setSelectionColor(new java.awt.Color(102, 102, 102));

        jlabel_username.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jlabel_username.setForeground(new java.awt.Color(51, 51, 51));
        jlabel_username.setText("Username");

        jlabel_password.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jlabel_password.setForeground(new java.awt.Color(51, 51, 51));
        jlabel_password.setText("Password");

        textfield_fullname.setBackground(new java.awt.Color(231, 231, 231));
        textfield_fullname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textfield_fullname.setForeground(new java.awt.Color(51, 51, 51));
        textfield_fullname.setSelectionColor(new java.awt.Color(102, 102, 102));

        jlabel_phone.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jlabel_phone.setForeground(new java.awt.Color(51, 51, 51));
        jlabel_phone.setText("Phone Number");

        textfield_email.setBackground(new java.awt.Color(231, 231, 231));
        textfield_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textfield_email.setForeground(new java.awt.Color(51, 51, 51));
        textfield_email.setSelectionColor(new java.awt.Color(102, 102, 102));

        textfield_phone.setBackground(new java.awt.Color(231, 231, 231));
        textfield_phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textfield_phone.setForeground(new java.awt.Color(51, 51, 51));
        textfield_phone.setSelectionColor(new java.awt.Color(102, 102, 102));

        jlabel_email.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jlabel_email.setForeground(new java.awt.Color(51, 51, 51));
        jlabel_email.setText("Email");

        jlabel_comfirmpassword.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jlabel_comfirmpassword.setForeground(new java.awt.Color(51, 51, 51));
        jlabel_comfirmpassword.setText("Comfirm Password");

        jbutton_register.setBackground(new java.awt.Color(253, 76, 90));
        jbutton_register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbutton_register.setForeground(new java.awt.Color(255, 255, 255));
        jbutton_register.setText("Register now");
        jbutton_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbutton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_registerActionPerformed(evt);
            }
        });

        jPasswordField_password.setBackground(new java.awt.Color(231, 231, 231));
        jPasswordField_password.setForeground(new java.awt.Color(51, 51, 51));

        jPasswordField_comfirmpassword.setBackground(new java.awt.Color(231, 231, 231));
        jPasswordField_comfirmpassword.setForeground(new java.awt.Color(51, 51, 51));

        jlabel_loginnow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlabel_loginnow.setForeground(new java.awt.Color(102, 102, 102));
        jlabel_loginnow.setText("Login Now");
        jlabel_loginnow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlabel_loginnow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_loginnowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_loginnowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_loginnowMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordField_comfirmpassword))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_email, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfield_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jalbel_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel_email, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jlabel_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textfield_username)
                                .addComponent(textfield_phone)
                                .addGroup(mainLayout.createSequentialGroup()
                                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlabel_comfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(6, 6, 6))
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jlabel_loginnow))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jbutton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jalbel_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_comfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_comfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jbutton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel_loginnow)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(backgroundtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_loginnowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_loginnowMouseClicked
        LoginForm login = new LoginForm();
        login.setVisible(true);
        login.pack();
        this.dispose();
    }//GEN-LAST:event_jlabel_loginnowMouseClicked

    private void jbutton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_registerActionPerformed
         try {
             if(verityFields() && checkUsername()){
                 user.setName(textfield_fullname.getText());
                 user.setPhone(textfield_phone.getText());
                 user.setUsername(textfield_username.getText());
                 user.setPassword(String.valueOf(jPasswordField_password.getPassword()));
                 user.setEmail(textfield_email.getText());
                 
                 userService.addUser(user);
                 JOptionPane.showMessageDialog (null, "Sign Up Success", "Success", 2);   
             }
         } catch (SQLException ex) {
             Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jbutton_registerActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void jlabel_loginnowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_loginnowMouseEntered
        Font font = new Font("Seoge UI",Font.BOLD,14);
        jlabel_loginnow.setFont(font);
    }//GEN-LAST:event_jlabel_loginnowMouseEntered

    private void jlabel_loginnowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_loginnowMouseExited
         Font font = new Font("Seoge UI",Font.PLAIN,14);
        jlabel_loginnow.setFont(font);
    }//GEN-LAST:event_jlabel_loginnowMouseExited
    public boolean verityFields(){
        String fname = textfield_fullname.getText ();
        String uname = textfield_username.getText ();
        String phone = textfield_phone.getText ();
        String email = textfield_email.getText();
        String pass1 = String.valueOf(jPasswordField_password.getPassword());
        String pass2 = String.valueOf(jPasswordField_comfirmpassword.getPassword ());
        // check empty fields
        if(fname.trim ().equals ("") || email.trim().equals("")  || uname.trim().equals ("") || phone.trim().equals ("") || pass1.trim ().equals ("")  || pass2.trim().equals ("")){
            JOptionPane.showMessageDialog (null, "One Or More Fields Are Empty", "Empty Fields", 2);
            return false;
        }
        // check if the two password are equals
        else if (!pass1.equals(pass2)){
           JOptionPane.showMessageDialog (null, "Password Doesn't Match", "User error", 2);
           return false;
        }
        else 
            return true;
        }
        public boolean checkUsername() throws SQLException{
                 String username = textfield_username.getText();
                 UserService us = new UserService();
                 if(us.checkUser(username)){
                          JOptionPane.showMessageDialog (null, "Your username already exists", "confirm Password", 2);
                          return false;
                 }
                 return true;
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundtitle;
    private javax.swing.JPasswordField jPasswordField_comfirmpassword;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JLabel jalbel_fullname;
    private javax.swing.JButton jbutton_register;
    private javax.swing.JLabel jlabel_comfirmpassword;
    private javax.swing.JLabel jlabel_email;
    private javax.swing.JLabel jlabel_loginnow;
    private javax.swing.JLabel jlabel_password;
    private javax.swing.JLabel jlabel_phone;
    private javax.swing.JLabel jlabel_username;
    private javax.swing.JPanel main;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField textfield_email;
    private javax.swing.JTextField textfield_fullname;
    private javax.swing.JTextField textfield_phone;
    private javax.swing.JTextField textfield_username;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
